version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: log_pipeline_db
    environment:
      POSTGRES_DB: log_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: log_pipeline_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5431
      DB_NAME: log_pipeline
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
